export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA';

export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SAVE_USER_SALARY = 'SAVE_USER_SALARY';